# -*- coding: utf-8 -*-
"""xGoalClustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m2MP3yqT3CYR34H2DCVxLxl4ndbxSsvY
"""

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('skaters.csv')

data2 = data.loc[data['situation']=='all']

twoD = data2.loc[:,["name",'team',"OnIce_F_xGoals","OnIce_A_xGoals","icetime"]]

twoD['per60'] = twoD['icetime']/3600

twoD['xG/60'] = twoD["OnIce_F_xGoals"]/twoD['per60']

twoD['xGA/60'] = twoD["OnIce_A_xGoals"]/twoD['per60']

twoD['error'] = twoD["xG/60"]-twoD['xGA/60']
twoD.head()

xGoalBins = [-np.inf,-1,0,1,np.inf]
group_names=['-1','-1-0','0-1','1+']
twoD['xGoalBins']=pd.cut(twoD['error'],xGoalBins,labels=group_names)

df0 = twoD[twoD.xGoalBins=='-1']
df1 = twoD[twoD.xGoalBins=='-1-0']
df2 = twoD[twoD.xGoalBins=='0-1']
df3 = twoD[twoD.xGoalBins=='1+']
x = np.linspace(0,5,100)
y = x
h = np.linspace(2.5,2.5,100)

plt_1 = plt.figure(figsize=(12, 12))
plt.scatter(df0['xG/60'],df0["xGA/60"],color = 'red')
plt.scatter(df1['xG/60'],df1["xGA/60"],color = 'orange')
plt.scatter(df2['xG/60'],df2["xGA/60"],color = 'blue')
plt.scatter(df3['xG/60'],df3["xGA/60"],color = 'green')

plt.plot(x,y,'--', color = 'black')
plt.plot(x,y-1,'--', color = 'green')
plt.plot(x,y+1,'--', color = 'red')

plt.xlim([0,5])
plt.ylim([0,5])
plt.legend(['even','+1','-1',])
plt.title("2021 Team xG vs xGA When Player is On the Ice")
plt.xlabel("Expected Goals")
plt.ylabel("Expected Goals Against")

